--CURRENCY

INSERT INTO CURRENCY (CURRENCY_CODE, CREATED_BY) VALUES ('SGD','SYSTEM');
INSERT INTO CURRENCY (CURRENCY_CODE, CREATED_BY) VALUES ('USD','SYSTEM');

--PERMISSIONS
INSERT INTO PERMISSIONS (PERMISSION, CREATED_BY) VALUES ('CLIENT','SYSTEM');